In [2]:
import numpy as np

In [3]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print("Data type of array is:", arr.dtype)

Data type of array is: int64


### **Dimension and Size of Array**

In [5]:
li2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [6]:
arr2 = np.array(li2)
print(arr2.dtype)
print(arr2 * 2)

int64
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [16]:
print("Data type of array is:", arr2.dtype, "\n")
print("Row X Column of array is:", arr2.shape, "\n")
print("Dimension of array is:", arr2.ndim, "\n")
print("Size (In Bytes) of array is:", arr2.nbytes, "\n")

Data type of array is: int64 

Row X Column of array is: (3, 3) 

Dimension of array is: 2 

Size (In Bytes) of array is: 72 



### **Concept of Reference and Copy**

In [17]:
li2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]

In [18]:
arr2 = np.array(li2)

int64


In [21]:
arr_ref = arr2 # Reference
arr_cp = arr2.copy() # Copy

In [33]:
arr_ref[0, 0] = 100

print("Reference of the original array: \n", arr_ref)
print("Changing reference, changes original array: \n", arr2)

Reference of the original array: 
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
Changing reference, changes original array: 
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
Memory location of the original array: 
 2010036638928
Memory location of the reference array: 
 2010036638928


In [29]:
arr_cp[0, 0] = 200

print("Copy of the original array: \n", arr_cp)
print("Changing copy, No changes in original array: \n", arr2)

Copy of the original array: 
 [[200   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
Changing copy, No changes in original array: 
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


### **Arrays memory location**

In [34]:
print("Memory location of the original array: \n", id(arr2))
print("Memory location of the reference array: \n", id(arr_ref))
print("Memory location of the copy array: \n", id(arr_cp))

Memory location of the original array: 
 2010036638928
Memory location of the reference array: 
 2010036638928
Memory location of the copy array: 
 2010036646608
