In [1]:
import numpy as np

In [3]:
data = np.genfromtxt('numpy_datasets/Mall_Customers_Int.csv',
                     delimiter=',',
                     skip_header=1)
data

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  3.,   0.,  20.,  16.,   6.],
       [  4.,   0.,  23.,  16.,  77.],
       [  5.,   0.,  31.,  17.,  40.],
       [  6.,   0.,  22.,  17.,  76.],
       [  7.,   0.,  35.,  18.,   6.],
       [  8.,   0.,  23.,  18.,  nan],
       [  9.,   1.,  64.,  19.,   3.],
       [ 10.,   0.,  30.,  19.,  72.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 12.,   0.,  35.,  19.,  99.],
       [ 13.,   0.,  58.,  nan,  15.],
       [ 14.,   0.,  24.,  20.,  77.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 17.,   0.,  35.,  21.,  nan],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 19.,   1.,  nan,  23.,  29.],
       [ 20.,   0.,  35.,  23.,  98.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 23.,   0.,  46.,  25.,   5.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 25.,   0.,  54.,  28.,  14.],
       [ 26.,   1.,  29.,

In [4]:
# Get total number rows and columns
data.shape

(200, 5)

Mask and use that as row and column argument

In [7]:
mask = data[:,1] == 1
mask[:10]

array([ True,  True, False, False, False, False, False, False,  True,
       False])

In [9]:
# Extract only those rows where mask is True
data[mask,:]

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  9.,   1.,  64.,  19.,   3.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 19.,   1.,  nan,  23.,  29.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 26.,   1.,  29.,  28.,  82.],
       [ 28.,   1.,  35.,  28.,  61.],
       [ 31.,   1.,  60.,  30.,   4.],
       [ 33.,   1.,  53.,  33.,   4.],
       [ 34.,   1.,  18.,  33.,  92.],
       [ 42.,   1.,  24.,  38.,  92.],
       [ 43.,   1.,  48.,  39.,  36.],
       [ 52.,   1.,  33.,  42.,  60.],
       [ 54.,   1.,  59.,  43.,  60.],
       [ 56.,   1.,  47.,  43.,  41.],
       [ 58.,   1.,  69.,  44.,  46.],
       [ 60.,   1.,  53.,  46.,  46.],
       [ 61.,   1.,  70.,  46.,  56.],
       [ 62.,   1.,  19.,  46.,  55.],
       [ 65.,   1.,  63.,

### **Extract Rows where any of the columns has missing value**

In [14]:
# Any checks any of the columns, axis indicates rowwise check
data[np.isnan(data).any(axis=1),:]

array([[  1.,   1.,  19.,  15.,  39.],
       [  2.,   1.,  21.,  15.,  81.],
       [  3.,   0.,  20.,  16.,   6.],
       [  4.,   0.,  23.,  16.,  77.],
       [  5.,   0.,  31.,  17.,  40.],
       [  6.,   0.,  22.,  17.,  76.],
       [  7.,   0.,  35.,  18.,   6.],
       [  9.,   1.,  64.,  19.,   3.],
       [ 10.,   0.,  30.,  19.,  72.],
       [ 11.,   1.,  67.,  19.,  14.],
       [ 12.,   0.,  35.,  19.,  99.],
       [ 14.,   0.,  24.,  20.,  77.],
       [ 15.,   1.,  37.,  20.,  13.],
       [ 16.,   1.,  22.,  20.,  79.],
       [ 18.,   1.,  20.,  21.,  66.],
       [ 20.,   0.,  35.,  23.,  98.],
       [ 21.,   1.,  35.,  24.,  35.],
       [ 22.,   1.,  25.,  24.,  73.],
       [ 23.,   0.,  46.,  25.,   5.],
       [ 24.,   1.,  31.,  25.,  73.],
       [ 25.,   0.,  54.,  28.,  14.],
       [ 26.,   1.,  29.,  28.,  82.],
       [ 28.,   1.,  35.,  28.,  61.],
       [ 29.,   0.,  40.,  29.,  31.],
       [ 30.,   0.,  23.,  29.,  87.],
       [ 31.,   1.,  60.,

In [12]:
np.isnan(data).any(axis=1)

array([False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False,  True, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [15]:
# Drop all row where any of the columns has missing value present, using negate operator
data[~np.isnan(data).any(axis=1),:]

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [17]:
# If a row contains a missing value, max return nan. Use nanmax instead to ignore such missing values
np.nanmax(data, axis=1)

array([ 39.,  81.,  20.,  77.,  40.,  76.,  35.,  23.,  64.,  72.,  67.,
        99.,  58.,  77.,  37.,  79.,  35.,  66.,  29.,  98.,  35.,  73.,
        46.,  73.,  54.,  82.,  45.,  61.,  40.,  87.,  60.,  73.,  53.,
        92.,  49.,  81.,  37.,  73.,  39.,  75.,  65.,  92.,  48.,  61.,
        49.,  65.,  55.,  48.,  49.,  50.,  52.,  60.,  54.,  60.,  55.,
        56.,  57.,  69.,  59.,  60.,  70.,  62.,  67.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [19]:
# If a column contains a missing value, max return nan. Use nanmax instead to ignore such missing values
np.nanmax(data, axis=0)

array([200.,   1.,  70., 137.,  99.])

#### **If-Else logic using np.where() function**

In [21]:
np.where(data[:,1]==1, data[:,4], data[:,4]/2)

array([39. , 81. ,  3. , 38.5, 20. , 38. ,  3. ,  nan,  3. , 36. , 14. ,
       49.5,  7.5, 38.5, 13. , 79. ,  nan, 66. , 29. , 49. , 35. , 73. ,
        2.5, 73. ,  7. , 82. , 16. , 61. , 15.5, 43.5,  4. , 36.5,  4. ,
       92. ,  7. , 40.5,  8.5, 36.5, 13. , 37.5, 17.5, 92. , 36. , 30.5,
       14. , 32.5, 27.5, 23.5, 21. , 21. , 26. , 60. , 27. , 60. , 22.5,
       41. , 25. , 46. , 25.5, 46. , 56. , 55. , 26. , 29.5, 51. , 59. ,
       25. , 24. , 59. , 23.5, 55. , 21. , 24.5, 28. , 47. , 54. , 26.5,
       48. , 26. , 21. , 51. , 55. , 41. , 22. , 28.5, 46. , 29. , 27.5,
       30. , 23. , 27.5, 41. , 49. , 20. , 21. , 52. , 23.5, 25. , 42. ,
       49. , 20.5, 24. , 59. , 55. , 56. , 21. , 25. , 46. , 43. , 48. ,
       52. , 27. , 21. , 46. , 24. , 25. , 21.5, 29.5, 21.5, 28.5, 56. ,
       20. , 29. , 91. , 14.5, 38.5, 35. , 95. , 11. , 75. ,  9. , 75. ,
       17. , 35.5,  5. , 44. ,  3.5, 73. , 10. , 36. ,  2.5, 93. , 20. ,
       43.5, 12. , 97. , 36. , 37. , 11. , 90. , 17

In [22]:
# Get the position of the maximum value in each row
np.argmax(data, axis=1)

array([4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 2, 4, 3, 4, 2, 4, 4, 4, 2, 4, 2, 4,
       2, 4, 2, 4, 3, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 0, 4, 2, 4, 2, 4,
       2, 4, 4, 0, 0, 0, 4, 4, 4, 4, 0, 0, 3, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [25]:
# Get the position of the maximum value in each row
max_pos=np.argmax(data, axis=1)

In [29]:
[data[row,col] for row, col in enumerate(max_pos)]

[np.float64(39.0),
 np.float64(81.0),
 np.float64(20.0),
 np.float64(77.0),
 np.float64(40.0),
 np.float64(76.0),
 np.float64(35.0),
 np.float64(nan),
 np.float64(64.0),
 np.float64(72.0),
 np.float64(67.0),
 np.float64(99.0),
 np.float64(nan),
 np.float64(77.0),
 np.float64(37.0),
 np.float64(79.0),
 np.float64(nan),
 np.float64(66.0),
 np.float64(nan),
 np.float64(98.0),
 np.float64(35.0),
 np.float64(73.0),
 np.float64(46.0),
 np.float64(73.0),
 np.float64(54.0),
 np.float64(82.0),
 np.float64(nan),
 np.float64(61.0),
 np.float64(40.0),
 np.float64(87.0),
 np.float64(60.0),
 np.float64(73.0),
 np.float64(53.0),
 np.float64(92.0),
 np.float64(49.0),
 np.float64(81.0),
 np.float64(nan),
 np.float64(73.0),
 np.float64(39.0),
 np.float64(75.0),
 np.float64(65.0),
 np.float64(92.0),
 np.float64(48.0),
 np.float64(61.0),
 np.float64(49.0),
 np.float64(65.0),
 np.float64(55.0),
 np.float64(48.0),
 np.float64(49.0),
 np.float64(50.0),
 np.float64(52.0),
 np.float64(60.0),
 np.float64(54.0),

#### **Get the position of the value where given condition is satisfied**

In [31]:
pos = np.argwhere(data[:,1]==1)
pos[:10]

array([[ 0],
       [ 1],
       [ 8],
       [10],
       [14],
       [15],
       [17],
       [18],
       [20],
       [21]])

### **Mini Challenge**

In [32]:
data = np.genfromtxt('numpy_datasets/Mall_Customers_Int.csv',
                     delimiter=',',
                     skip_header=1)

In [48]:
# Solution 1
pos=np.argwhere((data[:,1] == 1) & (data[:,2] < 21))
pos[:5]

array([[ 0],
       [17],
       [33],
       [61],
       [65]])

In [52]:
# Solution 1
arr = np.where((data[:,1] == 1) & (data[:,2] < 21), 1, 0)
data[:5,:]

array([[ 1.,  1., 19., 15., 39.],
       [ 2.,  1., 21., 15., 81.],
       [ 3.,  0., 20., 16.,  6.],
       [ 4.,  0., 23., 16., 77.],
       [ 5.,  0., 31., 17., 40.]])