In [2]:
import numpy as np

In [3]:
np.nan

nan

### **Comparison operations**

In [4]:
np.nan == np.nan

False

In [5]:
np.nan in [np.nan]

True

In [6]:
np.nan is np.nan

True

### **Import missing data file**

In [13]:
data = np.genfromtxt('numpy_datasets/data_miss.txt', delimiter='\t')
data

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     ,  2.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 7.     , 43.     , 39.62271],
       [ 8.     , 47.     , 34.95107],
       [ 9.     ,  2.     ,      nan],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894],
       [12.     , 24.     ,      inf],
       [13.     , 61.     , 72.55357],
       [14.     , 85.     , 39.24693],
       [15.     , 63.     , 53.6279 ],
       [16.     ,  2.     , 16.72441],
       [17.     , 29.     ,      nan],
       [18.     , 45.     , 18.78498],
       [19.     , 33.     , 19.8089 ],
       [20.     , 28.     , 46.03384],
       [21.     , 21.     , 23.7864 ],
       [22.     , 27.     , 44.42627],
       [23.     , 65.     , 34.94804],
       [24.     , 61.     , 53.49576],
       [25.     , 10.     , 25.98564]])

In [12]:
np.isnan(data) | np.isinf(data)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

### **Fill up missing values with some data**

In [15]:
data[np.isnan(data) | np.isinf(data)] = 0
print(data)

[[ 1.      87.      57.54435]
 [ 2.       8.       7.31704]
 [ 3.      56.      56.82095]
 [ 4.      63.      64.15579]
 [ 5.       2.       5.74522]
 [ 6.      45.      19.56758]
 [ 7.      43.      39.62271]
 [ 8.      47.      34.95107]
 [ 9.       2.       0.     ]
 [10.      79.      36.41022]
 [11.      67.      49.83894]
 [12.      24.       0.     ]
 [13.      61.      72.55357]
 [14.      85.      39.24693]
 [15.      63.      53.6279 ]
 [16.       2.      16.72441]
 [17.      29.       0.     ]
 [18.      45.      18.78498]
 [19.      33.      19.8089 ]
 [20.      28.      46.03384]
 [21.      21.      23.7864 ]
 [22.      27.      44.42627]
 [23.      65.      34.94804]
 [24.      61.      53.49576]
 [25.      10.      25.98564]]
