In [9]:
import numpy as np

In [11]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(arr.dtype)
print(arr * 2)

int64
[ 2  4  6  8 10]


### **Reversing the array**

In [27]:
arr[-1:-6:-1]

array([5, 4, 3, 2, 1])

### **Two Dimensional Arrays**

In [29]:
li2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [35]:
arr2 = np.array(li2)
print(arr2.dtype)
print(arr2 * 3)

int64
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### **Array Indexing**

In [40]:
arr2[0,:]

array([1, 2, 3])

In [42]:
arr2[:,1]

array([2, 5, 8])

### **Convert datatype of an array**

In [45]:
# converting from INT TO STR
arr2.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [46]:
# converting from INT TO FLOAT
arr2.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### **Mathematical Operations**

In [58]:
# Multiply array by 2
arr3 = arr2 * 2
print("Multiply array by 2 gives:\n", arr3, "\n")

# Divide array by 4
arr4 =  arr2 / 4
print("Divide array by 4 gives:\n", arr4, "\n")

# Addition of two arrays of same dimensions
add_arr = arr2 + arr3
print("Addition of two arrays:\n", add_arr)

Multiply array by 2 gives:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

Divide array by 4 gives:
 [[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]] 

Addition of two arrays:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### **Convert back to list**

In [37]:
new_list = arr2.tolist()
print(new_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
