### **Import Export of Data**

In [1]:
import numpy as np

In [13]:
# Load data using numpy
data = np.loadtxt("numpy_datasets/data.txt", delimiter="\t")
print(data)
print(type(data))

[[ 1.      87.      57.54435]
 [ 2.       8.       7.31704]
 [ 3.      56.      56.82095]
 [ 4.      63.      64.15579]
 [ 5.       2.       5.74522]
 [ 6.      45.      19.56758]
 [ 7.      43.      39.62271]
 [ 8.      47.      34.95107]
 [ 9.       2.       9.38692]
 [10.      79.      36.41022]
 [11.      67.      49.83894]
 [12.      24.      23.47974]
 [13.      61.      72.55357]
 [14.      85.      39.24693]
 [15.      63.      53.6279 ]
 [16.       2.      16.72441]
 [17.      29.      37.25533]
 [18.      45.      18.78498]
 [19.      33.      19.8089 ]
 [20.      28.      46.03384]
 [21.      21.      23.7864 ]
 [22.      27.      44.42627]
 [23.      65.      34.94804]
 [24.      61.      53.49576]
 [25.      10.      25.98564]]
<class 'numpy.ndarray'>


### **Where there is missing data**

In [14]:
# Load another file containing missing data
data_miss = np.genfromtxt("numpy_datasets/data_miss.txt", delimiter="\t")
print(data_miss)
print(type(data_miss))

[[ 1.      87.      57.54435]
 [ 2.       8.       7.31704]
 [ 3.      56.      56.82095]
 [ 4.      63.      64.15579]
 [ 5.       2.       5.74522]
 [ 6.      45.      19.56758]
 [ 7.      43.      39.62271]
 [ 8.      47.      34.95107]
 [ 9.       2.           nan]
 [10.      79.      36.41022]
 [11.      67.      49.83894]
 [12.      24.           inf]
 [13.      61.      72.55357]
 [14.      85.      39.24693]
 [15.      63.      53.6279 ]
 [16.       2.      16.72441]
 [17.      29.           nan]
 [18.      45.      18.78498]
 [19.      33.      19.8089 ]
 [20.      28.      46.03384]
 [21.      21.      23.7864 ]
 [22.      27.      44.42627]
 [23.      65.      34.94804]
 [24.      61.      53.49576]
 [25.      10.      25.98564]]
<class 'numpy.ndarray'>


### **Import CSV data file**

In [18]:
data = np.genfromtxt("numpy_datasets/Mall_Customers.csv",
                     delimiter=",",
                     dtype="object",
                     skip_header=1)
data

array([[b'1', b'Male', b'19', b'15', b'39'],
       [b'2', b'Male', b'21', b'15', b'81'],
       [b'3', b'Female', b'20', b'16', b'6'],
       [b'4', b'Female', b'23', b'16', b'77'],
       [b'5', b'Female', b'31', b'17', b'40'],
       [b'6', b'Female', b'22', b'17', b'76'],
       [b'7', b'Female', b'35', b'18', b'6'],
       [b'8', b'Female', b'23', b'18', b'94'],
       [b'9', b'Male', b'64', b'19', b'3'],
       [b'10', b'Female', b'30', b'19', b'72'],
       [b'11', b'Male', b'67', b'19', b'14'],
       [b'12', b'Female', b'35', b'19', b'99'],
       [b'13', b'Female', b'58', b'20', b'15'],
       [b'14', b'Female', b'24', b'20', b'77'],
       [b'15', b'Male', b'37', b'20', b'13'],
       [b'16', b'Male', b'22', b'20', b'79'],
       [b'17', b'Female', b'35', b'21', b'35'],
       [b'18', b'Male', b'20', b'21', b'66'],
       [b'19', b'Male', b'52', b'23', b'29'],
       [b'20', b'Female', b'35', b'23', b'98'],
       [b'21', b'Male', b'35', b'24', b'35'],
       [b'22', b'Male'

In [21]:
# Explicitly converting to float and do the opertions. Not a convenient way
output = data[:,3].astype('float') / data[:,2].astype('float')
print(output)

[0.78947368 0.71428571 0.8        0.69565217 0.5483871  0.77272727
 0.51428571 0.7826087  0.296875   0.63333333 0.28358209 0.54285714
 0.34482759 0.83333333 0.54054054 0.90909091 0.6        1.05
 0.44230769 0.65714286 0.68571429 0.96       0.54347826 0.80645161
 0.51851852 0.96551724 0.62222222 0.8        0.725      1.26086957
 0.5        1.42857143 0.62264151 1.83333333 0.67346939 1.57142857
 0.80952381 1.13333333 1.02777778 1.85       0.58461538 1.58333333
 0.8125     1.25806452 0.79591837 1.625      0.8        1.48148148
 1.37931034 1.29032258 0.85714286 1.27272727 1.38709677 0.72881356
 0.86       0.91489362 0.8627451  0.63768116 1.7037037  0.86792453
 0.65714286 2.42105263 0.70149254 0.87037037 0.76190476 2.66666667
 1.11627907 0.70588235 2.52631579 1.5        0.7        1.04255319
 0.83333333 0.83333333 0.91525424 2.07692308 1.2        1.35
 2.34782609 1.10204082 0.94736842 1.42105263 0.80597015 1.17391304
 2.57142857 1.125      1.03636364 2.59090909 1.70588235 1.16
 0.86764706 3

### **Better way to define datatype and import**

In [23]:
dt = np.dtype({"names": ["CustomerID","Genre","Age","Annual_Income","Spending_Score"],
               "formats": [np.int16, 'U16', np.int16, np.int16, np.int16]
              })

In [36]:
data = np.genfromtxt("numpy_datasets/Mall_Customers.csv",
                     delimiter=",",
                     dtype=dt,
                     skip_header=1)
data

array([(  1, 'Male', 19,  15, 39), (  2, 'Male', 21,  15, 81),
       (  3, 'Female', 20,  16,  6), (  4, 'Female', 23,  16, 77),
       (  5, 'Female', 31,  17, 40), (  6, 'Female', 22,  17, 76),
       (  7, 'Female', 35,  18,  6), (  8, 'Female', 23,  18, 94),
       (  9, 'Male', 64,  19,  3), ( 10, 'Female', 30,  19, 72),
       ( 11, 'Male', 67,  19, 14), ( 12, 'Female', 35,  19, 99),
       ( 13, 'Female', 58,  20, 15), ( 14, 'Female', 24,  20, 77),
       ( 15, 'Male', 37,  20, 13), ( 16, 'Male', 22,  20, 79),
       ( 17, 'Female', 35,  21, 35), ( 18, 'Male', 20,  21, 66),
       ( 19, 'Male', 52,  23, 29), ( 20, 'Female', 35,  23, 98),
       ( 21, 'Male', 35,  24, 35), ( 22, 'Male', 25,  24, 73),
       ( 23, 'Female', 46,  25,  5), ( 24, 'Male', 31,  25, 73),
       ( 25, 'Female', 54,  28, 14), ( 26, 'Male', 29,  28, 82),
       ( 27, 'Female', 45,  28, 32), ( 28, 'Male', 35,  28, 61),
       ( 29, 'Female', 40,  29, 31), ( 30, 'Female', 23,  29, 87),
       ( 31, 'Male', 

In [37]:
print("Total no. of dimension", data.ndim)
print(data[0]['Genre'])
print("Display all age values: \n", data['Age'])

Total no. of dimension 1
Male
Display all age values: 
 [19 21 20 23 31 22 35 23 64 30 67 35 58 24 37 22 35 20 52 35 35 25 46 31
 54 29 45 35 40 23 60 21 53 18 49 21 42 30 36 20 65 24 48 31 49 24 50 27
 29 31 49 33 31 59 50 47 51 69 27 53 70 19 67 54 63 18 43 68 19 32 70 47
 60 60 59 26 45 40 23 49 57 38 67 46 21 48 55 22 34 50 68 18 48 40 32 24
 47 27 48 20 23 49 67 26 49 21 66 54 68 66 65 19 38 19 18 19 63 49 51 50
 27 38 40 39 23 31 43 40 59 38 47 39 25 31 20 29 44 32 19 35 57 32 28 32
 25 28 48 32 34 34 43 39 44 38 47 27 37 30 34 30 56 29 19 31 50 36 42 33
 36 32 40 28 36 36 52 30 58 27 59 35 37 32 46 29 41 30 54 28 41 36 34 32
 33 38 47 35 45 32 32 30]


## **Save output to a file**

In [41]:
# Storing one array
np.save("TEMP/output.npy", data)

array([(  1, 'Male', 19,  15, 39), (  2, 'Male', 21,  15, 81),
       (  3, 'Female', 20,  16,  6), (  4, 'Female', 23,  16, 77),
       (  5, 'Female', 31,  17, 40), (  6, 'Female', 22,  17, 76),
       (  7, 'Female', 35,  18,  6), (  8, 'Female', 23,  18, 94),
       (  9, 'Male', 64,  19,  3), ( 10, 'Female', 30,  19, 72),
       ( 11, 'Male', 67,  19, 14), ( 12, 'Female', 35,  19, 99),
       ( 13, 'Female', 58,  20, 15), ( 14, 'Female', 24,  20, 77),
       ( 15, 'Male', 37,  20, 13), ( 16, 'Male', 22,  20, 79),
       ( 17, 'Female', 35,  21, 35), ( 18, 'Male', 20,  21, 66),
       ( 19, 'Male', 52,  23, 29), ( 20, 'Female', 35,  23, 98),
       ( 21, 'Male', 35,  24, 35), ( 22, 'Male', 25,  24, 73),
       ( 23, 'Female', 46,  25,  5), ( 24, 'Male', 31,  25, 73),
       ( 25, 'Female', 54,  28, 14), ( 26, 'Male', 29,  28, 82),
       ( 27, 'Female', 45,  28, 32), ( 28, 'Male', 35,  28, 61),
       ( 29, 'Female', 40,  29, 31), ( 30, 'Female', 23,  29, 87),
       ( 31, 'Male', 

In [46]:
#load data back from the file
data = np.load("TEMP/output.npy")
print(data[1]['Age'])
print(data['Genre'])

21
['Male' 'Male' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female'
 'Male' 'Female' 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female'
 'Male' 'Male' 'Female' 'Male' 'Male' 'Female' 'Male' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Female' 'Male' 'Female' 'Male' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Male' 'Male'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female'
 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male' 'Female' 'Male'
 'Male' 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Male' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Male'
 'Female' 'Female' 'Male' 'Male' 'Male' 'Female' 'Female' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female'
 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male' 'Male'
 'Male' 'Female' 'Female' 'Male' 'Male' 'Male' 'Male' 'Female' 'Female'
 'Male' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' '

In [47]:
# Storing multi dimensional array
np.savez("TEMP/outputs.npz", data, output)

In [53]:
#load data back from the file
f = np.load("TEMP/outputs.npz", allow_pickle=True)
f.files

['arr_0', 'arr_1']

In [55]:
print(f['arr_0'])

[(  1, 'Male', 19,  15, 39) (  2, 'Male', 21,  15, 81)
 (  3, 'Female', 20,  16,  6) (  4, 'Female', 23,  16, 77)
 (  5, 'Female', 31,  17, 40) (  6, 'Female', 22,  17, 76)
 (  7, 'Female', 35,  18,  6) (  8, 'Female', 23,  18, 94)
 (  9, 'Male', 64,  19,  3) ( 10, 'Female', 30,  19, 72)
 ( 11, 'Male', 67,  19, 14) ( 12, 'Female', 35,  19, 99)
 ( 13, 'Female', 58,  20, 15) ( 14, 'Female', 24,  20, 77)
 ( 15, 'Male', 37,  20, 13) ( 16, 'Male', 22,  20, 79)
 ( 17, 'Female', 35,  21, 35) ( 18, 'Male', 20,  21, 66)
 ( 19, 'Male', 52,  23, 29) ( 20, 'Female', 35,  23, 98)
 ( 21, 'Male', 35,  24, 35) ( 22, 'Male', 25,  24, 73)
 ( 23, 'Female', 46,  25,  5) ( 24, 'Male', 31,  25, 73)
 ( 25, 'Female', 54,  28, 14) ( 26, 'Male', 29,  28, 82)
 ( 27, 'Female', 45,  28, 32) ( 28, 'Male', 35,  28, 61)
 ( 29, 'Female', 40,  29, 31) ( 30, 'Female', 23,  29, 87)
 ( 31, 'Male', 60,  30,  4) ( 32, 'Female', 21,  30, 73)
 ( 33, 'Male', 53,  33,  4) ( 34, 'Male', 18,  33, 92)
 ( 35, 'Female', 49,  33, 14)